### PR TITLE
image component

### PR DESCRIPTION
**Pull request by bartlomiejdanek**
Just display image (without file upload field - could be added as optional parameter)
Sample usage:

```
form do
  field :image, :type => :image, :image => {:style => :original}
end
```

Default style: thumb.

### CODE REVIEW

**Comment by pyromaniac** [comment]
Hm, ok, but why do you need this? If you want just display image at form, without fields, do you need such view? Maybe, it chould look simplier? Just like this, for example:

```
<%= image_tag @record.send(field.name.to_sym).send(field.options[:image][:style]).url %>
```

Also, i think, at core there should be only basic components. I can not imagine, where this image components could be used. Give me examples please.

Also, why not to add index action similar to form?

And the latest. Let me explain: i've planned to implement something like paperclip component or carrierwave component together with general file_component. Why do we need separated components? Because of differences in plugins APIs. Also your image components works only for carriervawe. True? Now then autodetection will be implemented like here: https://github.com/puffer/puffer/blob/master/lib/puffer.rb#L122-130 And i've planned that this components will show file input, some kind of thumbnail if the image is present (just like you did) and also the remove checkbox or link etc.

What do you think? If you want exactly i've explaned - you may implement it even for one attachment plugin you like and i'll include it to core.

Thanks for you concernment!

**Comment by bartlomiejdanek** [comment]
For instance
I upload image and I want to see preview.

Correct - its only works with carrierwave, but I don't see problem to define method f.e. `url` and check processor for given record.
Of course it would be fine to have component which has support for carrierwave/paprerclicp.

**Comment by pyromaniac** [comment]
Ok, can you create complete carriervawe component like i've explaned earlier? I think, it will be the best solution.

**Comment by bartlomiejdanek** [comment]
Sure, probably'll send you next pull request today evening.

**Comment by pyromaniac** [comment]
Hi, take a look please, I've implemented carrierwave component

**Pull request closed without merging**
